package com.minivest.mutualfunds.entity;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.minivest.mutualfunds.enums.TransactionStatus;
import com.minivest.mutualfunds.enums.TransactionType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "transactions")
public class Transaction {
    // making in an primary key
    // auto generated by database, so we don't have to worry about it in code
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // we will add the coloumn in database as user_id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
 
    @Column(nullable = false)
    private BigDecimal amount;

    // Store enum as STRING in DB (not ordinal number).
    // "LUMPSUM" in DB is much clearer than "0" when debugging.
    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type", nullable = false)
    private TransactionType type;

    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_status", nullable = false)
    private TransactionStatus status;

    // Created when order is created.
    @Column(name = "razorpay_payment_id")
    private String razorpayOrderId;
    
    // Set after payment is captured.
    // unique = true → prevents processing same payment twice (idempotency!).
    @Column(name = "razorpay_payment_id", unique = true)
    private String razorpapPaymentId;
    
    @Column(name = "razorpay_signature")
    private String razorpaySignature;

    @Column(name = "razorpay_refund_id", unique = true)
    private String razorpayRefundId;

    @Column(name = "scheme_name")
    private String schemeName;

    @Column(name = "payment_method")
    private String paymentMethod;

    @Column(name = "failure_reason")
    private String failureReason;
    
    @Column(name = "created_at")
    private LocalDateTime createdAt;
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate(){
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }   

    @PreUpdate
    protected void onUpdate(){
        updatedAt = LocalDateTime.now();
    }
}
