package com.minivest.mutualfunds.entity;


import com.minivest.mutualfunds.enums.TransactionStatus;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Transaction {
    // making in an primary key
    // auto generated by database, so we don't have to worry about it in code
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    private String razorpayOrderId;
    private String schemeName;
    private Double amount;

    @NotNull(message = "Transaction status cannot be null")
    private TransactionStatus status;
    
    private java.time.LocalDateTime createdAt;
}
